-- Auto-generated UCG schema for DuckDB
CREATE TABLE nodes AS SELECT * FROM read_parquet('nodes/*.parquet');
CREATE TABLE edges AS SELECT * FROM read_parquet('edges/*.parquet');
CREATE TABLE anomalies AS SELECT * FROM read_parquet('anomalies/*.parquet');
CREATE TABLE cfg_blocks AS SELECT * FROM read_parquet('cfg_blocks/*.parquet');
CREATE TABLE cfg_edges AS SELECT * FROM read_parquet('cfg_edges/*.parquet');
CREATE TABLE dfg_nodes AS SELECT * FROM read_parquet('dfg_nodes/*.parquet');
CREATE TABLE dfg_edges AS SELECT * FROM read_parquet('dfg_edges/*.parquet');
CREATE TABLE symbols AS SELECT * FROM read_parquet('symbols/*.parquet');
CREATE TABLE aliases AS SELECT * FROM read_parquet('aliases/*.parquet');
CREATE TABLE effects AS SELECT * FROM read_parquet('effects/*.parquet');
CREATE TABLE nodes_v2 AS SELECT * FROM read_parquet('nodes_v2/*.parquet');
CREATE TABLE edges_v2 AS SELECT * FROM read_parquet('edges_v2/*.parquet');
CREATE TABLE cfg_blocks_v2 AS SELECT * FROM read_parquet('cfg_blocks_v2/*.parquet');
CREATE TABLE cfg_edges_v2 AS SELECT * FROM read_parquet('cfg_edges_v2/*.parquet');
CREATE TABLE dfg_nodes_v2 AS SELECT * FROM read_parquet('dfg_nodes_v2/*.parquet');
CREATE TABLE dfg_edges_v2 AS SELECT * FROM read_parquet('dfg_edges_v2/*.parquet');
CREATE TABLE symbols_v2 AS SELECT * FROM read_parquet('symbols_v2/*.parquet');
CREATE TABLE aliases_v2 AS SELECT * FROM read_parquet('aliases_v2/*.parquet');
CREATE TABLE effects_v2 AS SELECT * FROM read_parquet('effects_v2/*.parquet');
CREATE TABLE scopes_v2 AS SELECT * FROM read_parquet('scopes_v2/*.parquet');
CREATE TABLE symbols_scopes_v2 AS SELECT * FROM read_parquet('symbols_scopes_v2/*.parquet');

-- Suggested indexes
CREATE INDEX idx_nodes_kind ON nodes(kind);
CREATE INDEX idx_nodes_path ON nodes(path);
CREATE INDEX idx_edges_src ON edges(src_id);
CREATE INDEX idx_edges_dst ON edges(dst_id);
CREATE INDEX idx_cfg_blocks_func ON cfg_blocks(func_id);
CREATE INDEX idx_cfg_edges_src ON cfg_edges(src_block_id);
CREATE INDEX idx_cfg_edges_dst ON cfg_edges(dst_block_id);
CREATE INDEX idx_dfg_nodes_func ON dfg_nodes(func_id);
CREATE INDEX idx_dfg_nodes_name ON dfg_nodes(name);
CREATE INDEX idx_dfg_edges_src ON dfg_edges(src_id);
CREATE INDEX idx_dfg_edges_dst ON dfg_edges(dst_id);
CREATE INDEX idx_symbols_scope ON symbols(scope_id);
CREATE INDEX idx_symbols_name ON symbols(name);
CREATE INDEX idx_aliases_kind ON aliases(alias_kind);
CREATE INDEX idx_aliases_alias ON aliases(alias_id);
CREATE INDEX idx_aliases_tgt ON aliases(target_symbol_id);
CREATE INDEX idx_effects_kind ON effects(kind);
CREATE INDEX idx_effects_carr ON effects(carrier);
CREATE INDEX idx_effects_path ON effects(path);
CREATE INDEX idx_nodes_v2_kind ON nodes_v2(kind);
CREATE INDEX idx_nodes_v2_path ON nodes_v2(path);
CREATE INDEX idx_edges_v2_src ON edges_v2(src_id);
CREATE INDEX idx_edges_v2_dst ON edges_v2(dst_id);
CREATE INDEX idx_cfg_blocks_v2_func ON cfg_blocks_v2(func_id);
CREATE INDEX idx_cfg_edges_v2_src ON cfg_edges_v2(src_block_id);
CREATE INDEX idx_cfg_edges_v2_dst ON cfg_edges_v2(dst_block_id);
CREATE INDEX idx_dfg_nodes_v2_func ON dfg_nodes_v2(func_id);
CREATE INDEX idx_dfg_nodes_v2_name ON dfg_nodes_v2(name);
CREATE INDEX idx_dfg_edges_v2_src ON dfg_edges_v2(src_id);
CREATE INDEX idx_dfg_edges_v2_dst ON dfg_edges_v2(dst_id);
CREATE INDEX idx_symbols_v2_scope ON symbols_v2(scope_id);
CREATE INDEX idx_symbols_v2_name ON symbols_v2(name);
CREATE INDEX idx_aliases_v2_kind ON aliases_v2(alias_kind);
CREATE INDEX idx_aliases_v2_alias ON aliases_v2(alias_id);
CREATE INDEX idx_aliases_v2_tgt ON aliases_v2(target_symbol_id);
CREATE INDEX idx_effects_v2_kind ON effects_v2(kind);
CREATE INDEX idx_effects_v2_carr ON effects_v2(carrier);
CREATE INDEX idx_effects_v2_path ON effects_v2(path);
CREATE INDEX idx_scopes_v2_kind ON scopes_v2(kind);
CREATE INDEX idx_scopes_v2_path ON scopes_v2(path);
CREATE INDEX idx_symbols_scopes_v2_scope ON symbols_scopes_v2(scope_id);
CREATE INDEX idx_symbols_scopes_v2_symbol ON symbols_scopes_v2(symbol_id);