# When a new tag is created, this workflow will open a PR
# to update the demo branch with the latest code from the main branch

name: "🎈 Update Demo"

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  create-demo-PR:
    runs-on: ubuntu-latest

    steps:
      - name: Set TAG environment variable
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Checkout demo branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0
          ref: demo

      - name: Merge main into demo
        run: |
          # Configure Git to commit as your bot
          git config user.name "liss-bot"
          git config user.email "alicia-gh-bot@mail.as93.net"

          # Fetch main and merge it into local demo
          git fetch origin main
          git merge origin/main --no-edit
          # If there's a merge conflict, the job will fail unless you handle it

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.BOT_TOKEN }}
          base: demo
          branch: "bot/update-demo"
          title: "Update Demo Branch from Main"
          body: |
            A new tag **${{ env.TAG }}** was just pushed!

            🤖 Let's merge the latest changes **`main`** → **`demo`**,
            so that the demo environment is updated to version ${{ env.TAG }}.

            <details>
            <summary>🔍 View Context</summary>

            - Repository: ${{ github.repository }}
            - Tag Reference: ${{ github.ref }}
            - Tag Name: ${{ env.TAG }}
            - Workflow Run: ${{ github.run_id }}
            - Commit SHA: ${{ github.sha }}

            </details>

            > [!NOTE]
            > Merging this PR will incorporate the latest changes from main
            > into the demo branch, which will promote the latest updates to the demo environment,
            > deploying it to [demo.domain-locker.com](https://demo.domain-locker.com).

