app:
  image: lissy93/domain-locker:latest
  port: 3000
  env:
    DL_ENV_TYPE: selfHosted
    DL_PG_HOST: domain-locker-postgres
    DL_PG_PORT: 5432
    DL_PG_USER: postgres
    DL_PG_PASSWORD: changeme2420
    DL_PG_NAME: domain_locker
  ingress:
    enabled: true
    # ingressClassName: "nginx"
    annotations: # nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
    - host: domain-locker.localhost.com
      paths:
      - path: /
        service:
          name: domain-locker-app
          port: 80
    # tls:
    # - hosts:
    #   - domain-locker.localhost.com
    #   secretName: domain-locker.localhost.com-tls

postgres:
  image: postgres:15-alpine
  port: 5432
  env:
    POSTGRES_DB: domain_locker
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: changeme2420
  persistence:
    enabled: true
    size: 1Gi

updater:
  enabled: true
