name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip ruff mypy pytest
      - name: Lint
        run: . .venv/bin/activate && ruff check .
      - name: Typecheck
        run: . .venv/bin/activate && mypy src || true
      - name: Tests
        run: . .venv/bin/activate && pytest
